name: Merge to Main Branch

on:
  push:
    branches:
      - main

env:
  WORKING_DIR: './terraform'
  TF_LOG: ERROR
  TF_CLI_ARGS: "-no-color"
  TF_INPUT: false
  TF_IN_AUTOMATION: true

jobs:
  tf_apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}