name: Merge to Main branch

on:
  push:
    branches:
      - main

env:
  WORKING_DIR: './base'
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  tf_apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -no-color
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}