name: Pull Request Main

on:
  pull_request:
    branches:
      - main

env:
  WORKING_DIR: './base'
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      id: tf_init
      run: terraform init
      continue-on-error: true

    - name: Terraform Format
      id: tf_fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Validate
      id: tf_validate
      run: terraform validate -no-color
      continue-on-error: true
    
    - name: Terraform Plan
      id: tf_plan
      run: terraform plan -no-color
      continue-on-error: true

    - uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          // 0. Create helper functions
          function emojiStatus(status) {
            return (status === 'success') ? '✅' : '❌'
          }
    
          // 1. Retrieve existing bot comments for the PR
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const ghaBotComment = comments.find(comment => {
            return (
              comment.user.type === 'Bot' &&
              comment.user.login === 'github-actions[bot]' &&
              comment.body.includes('Terraform Init')
            )
          })
    
          // 2. Prepare format of the comment
          const output =`
            #### ${emojiStatus('${{ steps.tf_init.outcome }}')} Terraform Init ⚙️

            #### ${emojiStatus('${{ steps.tf_fmt.outcome }}')} Terraform Format 🖌
            
            #### ${emojiStatus('${{ steps.tf_validate.outcome }}')} Terraform Validate 🤖
            <details><summary>Show Validation</summary>
            
            \`\`\`
            ${{ steps.tf_validate.outputs.stdout || steps.tf_validate.outputs.stderr }}
            \`\`\`
            
            </details>
            
            #### ${emojiStatus('${{ steps.tf_plan.outcome }}')} Terraform Plan 📖
            <details><summary>Show Plan</summary>
            
            \`\`\`
            ${{ steps.tf_plan.outputs.stdout || steps.tf_plan.outputs.stderr }}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}
            Action: \`${{ github.event_name }}\`
            Working Directory: \`${{ env.WORKING_DIR }}\`
            Workflow: \`${{ github.workflow }}\`*
          `;
    
          // 3. If we have a comment, update it, otherwise create a new one
          if (ghaBotComment) {
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ghaBotComment.id,
              body: output
            })
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
          }
    
          // 4. Fail the workflow if one of the steps failed
          const statuses = [
            '${{ steps.tf_init.outcome }}',
            '${{ steps.tf_fmt.outcome }}',
            '${{ steps.tf_validate.outcome }}',
            '${{ steps.tf_plan.outcome }}'
          ]
          if (statuses.includes("failure")) {
            core.setFailed("Terraform failed, check PR comment for details")
          }

          // 5. Update GITHUB_STEP_SUMMARY
          await core.summary
            .addHeading('Results')
            .addRaw(output)
            .write()